### ISSUE TITLE
Gecko Linux rolling

### ISSUE THREAD

**Issue by Malternative3772** [egee-irl/distro-delves#131]
## Name & tl;dr
Gecko Linux rolling (static releases are also available)

## What is the release date or cycle?
The static edidion uses the openSUSE release cycle

## Who is the target user?
People who want a "works out of the box" expericence with openSUSE. 

## What platforms does it support?
x86_64

## What makes it special?
It's one of the few openSUSE based distros that aim to be user- or maybe even beginner-friendly.

https://geckolinux.github.io

**Comment by Malternative3772** [comment]
Let's go with the LXQt edition :)

**Comment by egee-irl** [comment]
This one looks like a good next candidate :eyes:

**Comment by geckolinux** [comment]
Hi there @egee-irl , creator of GeckoLinux here. Thanks a lot for the thorough review! I'm glad that it worked well, apart from the fatal GRUB issue... So about that-- The issue happened because I enabled zstd compression for the Btrfs filesystem by default, and the openSUSE version of GRUB doesn't support it. I had thoroughly tested a workaround that appeared to, well, _work_, to enable zstd compression for the entire filesystem except `/boot`. So I'm not sure why that issue re-appeared. But the good news is that this issue will only happen on systems with a legacy BIOS (like your VirtualBox instance by default). Apart from that issue that was my fault, openSUSE Tumbleweed is actually incredibly reliable at doing `zypper dup` upgrades, I've had success at updating installations from ISOs that were almost 2 years old, with no issues at all. So I'm currently working on finalizing the next release of GeckoLinux so the GRUB issue doesn't happen again. Thanks a lot for catching that! As for the language installer script, the `zypper dup` step is optional with a "Y/N" prompt, but generally recommended first if language pack installation is desired. Or if you don't need non-English language support then there's no point in running the script.
