### ISSUE TITLE
Gaming Benchmark

### ISSUE THREAD

**Issue by ishan9299** [egee-irl/distro-delves#14]
## Add, Remove, or Update?

This is an addition, 
## Which Segment?

This should be placed in the under tweaking the system for gaming, there are some custom builds of wine which improve on gaming issues like sound and frame drop issues (check out [GloriousEggroll](https://github.com/GloriousEggroll) and [wine-tkg-git)](https://github.com/Tk-Glitch/PKGBUILDS/tree/master/wine-tkg-git)
## Rationale?

People who game on linux might want to look into these custom builds of wine and check out how easy is it configure their distro for gaming and also if documentation is available for their specific ditstro or derived distro when it comes to installing from source

**Comment by egee-irl** [comment]
I recently combined the "Gaming" section with the "Benchmarking" section and included benchmark results for GTA5 and Mad Max.

Having a section specifically for gaming performance or tweakage would make it a bit more than just a "distro review". Plus it would add a significant amount of time to the production of the video since every distro is a bit different in that regard.
