### ISSUE TITLE
openmamba

### ISSUE THREAD

**Issue by KaiLikesLinux** [egee-irl/distro-delves#25]
## Openmamba

Their Website: https://openmamba.org
## What is the release date or cycle?

It is rolling release, like Arch and OpenSUSE Tumbleweed. They used to have stable versions 
called Milestone, but those ended by milestone3 it seems/
## Who is the target user?

It is general-purpose it seems. Anything from servers, to desktop, to single boards.
## What platforms does it support?

x86_64 and i586
## What makes it special?
This is an oddly usable distribution for something I am sure no one has heard of. It is a wonderful distribution, with some mild issues.

**Comment by egee-irl** [comment]
What a strange little distro. Good find!

**Comment by egee-irl** [comment]
@KaiLikesLinux OpenMamba is a total mess. The internal tools don't work very good and all the mirrors are located in Europe (possibly only Italy) so the connection is extremely poor. And DNF is misconfigured and asks the user to accept the GPG keys _every single time_ DNF is run.

I'm going to pass on this one primarily due to the bad mirrors. It's just taking way too long to capture footage since everything moves at a snails pace.
