### ISSUE TITLE
Rewrite "Application Management" section

### ISSUE THREAD

**Issue by egee-irl** [egee-irl/distro-delves#7]
## Add, Remove, or Update?
Update

## Which Segment?
Application Management, specifically the _Install Apps_ section

## Rationale?
This section feels rather fluffy and I don't think it adds a lot of value to the episode. For example, almost all Linux distros will have Wine or Audacity available, and if they don't, so what?

In most episodes, I don't show the install of each application because it would take too long. Despite that, this segment takes about 60 seconds of screen time, which isn't great.

I'm also against including apps that come from Flathub in this section because Flatpak & Flathub are pretty easy to install on most distros and include most software an end-user would want. So, showing off installing Flatpak apps from Flathub doesn't tell us anything we don't already know.

[This](https://github.com/egee-irl/distro-delves/issues/3) issue that mcpower3 submitted suggests adding DaVinci Resolve or Unity3D, and I think that's an interesting idea, but most desktop users wouldn't need to install an application like Resolve for Unity3D.

So the proposed solution for this issue is:

Option 1: Remove the "Install Apps" section entirely since it doesn't currently add much value to episodes

Option 2: Rewrite the section to include troublesome apps like DaVinci Resolve, Unity3D, VMware, Lightworks, etc.

If you have any thoughts or opinions, let me know as a comment on this issue!

**Comment by Mcpower03** [comment]
Maybe remove all the "fluff" apps, ones that are available as flatpaks or appimages, any ubuntu based distro has all the apps in the ubuntu repos for example, maybe mention and oddities like elmemetry doesn't by default support ppa's. Maybe also try installing some of those more troublesome apps like you were saying, because I would think most people looking a more desktop distros want something that they can almost one click install their favorite windows programs that support linux. Some other potentially troublesome apps include Houdini, Maya, and any Jetbrains stuff

**Comment by Octokitty8961** [comment]
I would suggest option#2.  Using their own repos rather than flatpack/snaps. 
What do you consider the average user to be? I think installing VMware might be a good test. If you wanted to go down the gaming route, see how it handles Steam/Lutris etc.  I guess you'd want a set of packages that might cause issues but not send you too far down a rabbit hole to fix (and that is also when you see if the distro has good documentation/forums). 

Keep doing a fine job.

**Comment by Mcpower03** [comment]
Other potential idea
Talk breifly about what was in the repos and what had/could be done extra to get certain apps (The current app list)
Any issues or weird styling and things in those apps
Pick two difficult to install apps and try to install them, maybe an easier one and a harder one (Like the ones you mentioned)
Mention any weird issues in there
Wrap it up with any out of the ordinary stuff regaring package management
BTW, the new benchmarks/gaming is exactly where it should have went, kudos

**Comment by natri23** [comment]
I think the Application Management should be more about install common apps that a new Linux user would seek, like Chrome, Teamviewer and such. 
And not from the terminal cause ... "new user", say "my dad"

Flatpak is only important if it can be access from the Software Center

Also, why VMware? Why not use QEMU/KVM?

**Comment by egee-irl** [comment]
@natri23 because applications like VMware Player are problematic and the purpose of Distro Delves is to highlight when Distros have problems installing applications like that.

QEMU/KVM are similar but different in the wrong ways - they are hardware-specific and often take much more time to setup and configure than something like VMware Player does.

Either way, I'm not doing the virtualization thing because I don't think it adds much value to the section.

**Comment by egee-irl** [comment]
I've refactored the application management section and this task is no longer needed
